apiKey: 6777278635:AAG7ViHwyL4gFQzRmjWezkIITkD1LB8FYJg
fontPath: internal\config\arialmt.ttf
configPath: internal\config\yolov3-tiny-my.cfg
weightsPath: internal\config\yolov3-tiny-my_last.weights
threshold: 0.3
cacheCleanup: 5m
